version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
    - ./createdb.sql:/docker-entrypoint-initdb.d/createdb.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080